### ISSUE TITLE
crash report of xapp-sn-watcher

### ISSUE THREAD

**Issue by Lucafatichenti** [linuxmint/xapps#105] opened 2020-08-04 17:42 UTC
===================================================================
 Info                                                              
===================================================================
           PID: 1762 (xapp-sn-watcher)
           UID: 1000 (luca)
           GID: 1000 (luca)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-08-03 18:21:49 CEST (1 day 1h ago)
  Command Line: /usr/libexec/xapps/sn-watcher/xapp-sn-watcher
    Executable: /usr/libexec/xapps/sn-watcher/xapp-sn-watcher
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (luca)
       Boot ID: 36e78adf6edd4f85b5860a31ab7b0b47
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: luca-T4000-C4000
       Storage: /var/lib/systemd/coredump/core.xapp-sn-watcher.1000.36e78adf6edd4f85b5860a31ab7b0b47.1762.1596471709000000000000.lz4
       Message: Process 1762 (xapp-sn-watcher) of user 1000 dumped core.
                
                Stack trace of thread 1762:
                #0  0x00007f82745d86e4 n/a (libglib-2.0.so.0 + 0x876e4)
                #1  0x00007f82745d8b90 g_utf8_normalize (libglib-2.0.so.0 + 0x87b90)
                #2  0x00005649903a21c7 n/a (xapp-sn-watcher + 0x131c7)
                #3  0x00007f827478ef49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #4  0x00007f827478fb3d n/a (libgio-2.0.so.0 + 0xb5b3d)
                #5  0x00007f82747f589d n/a (libgio-2.0.so.0 + 0x11b89d)
                #6  0x00007f827478ef49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #7  0x00007f827478fb3d n/a (libgio-2.0.so.0 + 0xb5b3d)
                #8  0x00007f82747f4eb1 n/a (libgio-2.0.so.0 + 0x11aeb1)
                #9  0x00007f82747f4fec n/a (libgio-2.0.so.0 + 0x11afec)
                #10 0x00007f827478ef49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #11 0x00007f827478fb3d n/a (libgio-2.0.so.0 + 0xb5b3d)
                #12 0x00007f82747ea35f n/a (libgio-2.0.so.0 + 0x11035f)
                #13 0x00007f827478ef49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #14 0x00007f827478ef8d n/a (libgio-2.0.so.0 + 0xb4f8d)
                #15 0x00007f82745a2e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #16 0x00007f82745a3240 n/a (libglib-2.0.so.0 + 0x52240)
                #17 0x00007f82745a32e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #18 0x00007f82747bcfd5 g_application_run (libgio-2.0.so.0 + 0xe2fd5)
                #19 0x0000564990398da8 main (xapp-sn-watcher + 0x9da8)
                #20 0x00007f827396c0b3 __libc_start_main (libc.so.6 + 0x270b3)
                #21 0x0000564990398e0e _start (xapp-sn-watcher + 0x9e0e)
                
                Stack trace of thread 1779:
                #0  0x00007f8273a5a96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f82745a31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f82745a3533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f82747f8eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f82745cc931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f82736f6609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8273a67103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 12688:
                #0  0x00007f8273a6070d syscall (libc.so.6 + 0x11b70d)
                #1  0x00007f82745f05a6 g_cond_wait_until (libglib-2.0.so.0 + 0x9f5a6)
                #2  0x00007f8274573561 n/a (libglib-2.0.so.0 + 0x22561)
                #3  0x00007f8274573b86 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x22b86)
                #4  0x00007f82745cd279 n/a (libglib-2.0.so.0 + 0x7c279)
                #5  0x00007f82745cc931 n/a (libglib-2.0.so.0 + 0x7b931)
                #6  0x00007f82736f6609 start_thread (libpthread.so.0 + 0x9609)
                #7  0x00007f8273a67103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1778:
                #0  0x00007f8273a5a96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f82745a31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f82745a32e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f82745a3331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f82745cc931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f82736f6609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8273a67103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1780:
                #0  0x00007f8273a5a96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f82745a31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f82745a32e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f82748f999d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f82745cc931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f82736f6609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8273a67103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1762]
[New LWP 1779]
[New LWP 12688]
[New LWP 1778]
[New LWP 1780]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/xapps/sn-watcher/xapp-sn-watcher'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f82745d86e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f82707cea80 (LWP 1762))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1762]
[New LWP 1779]
[New LWP 12688]
[New LWP 1778]
[New LWP 1780]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/xapps/sn-watcher/xapp-sn-watcher'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f82745d86e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f82707cea80 (LWP 1762))]
#0  0x00007f82745d86e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f82745d8b90 in g_utf8_normalize () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00005649903a21c7 in ?? ()
#3  0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007f82747f589d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f82747f4eb1 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007f82747f4fec in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x00007f82747ea35f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007f827478ef8d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007f82745a2e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f82745a3240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f82745a32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f82747bcfd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x0000564990398da8 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1762]
[New LWP 1779]
[New LWP 12688]
[New LWP 1778]
[New LWP 1780]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/xapps/sn-watcher/xapp-sn-watcher'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f82745d86e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f82707cea80 (LWP 1762))]

Thread 5 (Thread 0x7f826f6d8700 (LWP 1780)):
#0  0x00007f8273a5a96f in __GI___poll (fds=0x564991d30bb0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f82745a31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f82745a32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f82748f999d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f82745cc931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f82736f6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140198191924992, -139714878551920627, 140730600351406, 140730600351407, 140730600351552, 140198191922304, 75291069051531277, 75229479688040461}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8273a67103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7f827071f700 (LWP 1778)):
#0  0x00007f8273a5a96f in __GI___poll (fds=0x564991d39db0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f82745a31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f82745a32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f82745a3331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f82745cc931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f82736f6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140198208993024, -139714878551920627, 140730600349694, 140730600349695, 140730600349840, 140198208990336, 75227405288173581, 75229479688040461}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8273a67103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f826e811700 (LWP 12688)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f82745f05a6 in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8274573561 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8274573b86 in g_async_queue_timeout_pop () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f82745cd279 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f82745cc931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007f82736f6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140198176429824, -139714878551920627, 140730600350494, 140730600350495, 140730600350640, 140198176427136, 75293512351051789, 75229479688040461}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007f8273a67103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f826ff1e700 (LWP 1779)):
#0  0x00007f8273a5a96f in __GI___poll (fds=0x564991d4f650, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f82745a31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f82745a3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f82747f8eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f82745cc931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f82736f6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140198200600320, -139714878551920627, 140730600350126, 140730600350127, 140730600350272, 140198200597632, 75292277011083277, 75229479688040461}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8273a67103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f82707cea80 (LWP 1762)):
#0  0x00007f82745d86e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007f82745d8b90 in g_utf8_normalize () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00005649903a21c7 in ?? ()
No symbol table info available.
#3  0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#5  0x00007f82747f589d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#6  0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#7  0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#8  0x00007f82747f4eb1 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#9  0x00007f82747f4fec in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#10 0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#11 0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#12 0x00007f82747ea35f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#13 0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#14 0x00007f827478ef8d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#15 0x00007f82745a2e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#16 0x00007f82745a3240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#17 0x00007f82745a32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0x00007f82747bcfd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#19 0x0000564990398da8 in main ()
No symbol table info available.
#0  0x00007f82745d86e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f82745d8b90 in g_utf8_normalize () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00005649903a21c7 in ?? ()
#3  0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007f82747f589d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f82747f4eb1 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007f82747f4fec in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007f827478fb3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x00007f82747ea35f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007f827478ef49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007f827478ef8d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007f82745a2e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f82745a3240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f82745a32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f82747bcfd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x0000564990398da8 in main ()

**Comment by mtwebster** [comment] 2020-08-04 17:59
Duplicate of https://github.com/linuxmint/xapps/issues/98

**Closed by mtwebster** 2020-08-04 17:59 UTC
